# Generated by Django 3.0.5 on 2020-05-16 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_notes_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notes',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
