# Generated by Django 3.0.5 on 2020-05-24 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200524_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='name',
            new_name='username',
        ),
    ]
