# Generated by Django 3.0.5 on 2020-05-24 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200524_2105'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
