# Generated by Django 3.0.5 on 2020-05-25 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_website_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='created_date',
        ),
    ]
