# Generated by Django 3.0.5 on 2020-05-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20200525_1609'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
        migrations.AddField(
            model_name='website',
            name='user',
            field=models.CharField(default='user', max_length=255),
        ),
    ]
