# Generated by Django 3.0.5 on 2020-05-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20200525_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='description',
        ),
        migrations.RemoveField(
            model_name='website',
            name='menu1',
        ),
        migrations.RemoveField(
            model_name='website',
            name='menu2',
        ),
        migrations.RemoveField(
            model_name='website',
            name='menu3',
        ),
        migrations.RemoveField(
            model_name='website',
            name='menu4',
        ),
        migrations.RemoveField(
            model_name='website',
            name='menu5',
        ),
        migrations.RemoveField(
            model_name='website',
            name='menus',
        ),
        migrations.RemoveField(
            model_name='website',
            name='title',
        ),
        migrations.RemoveField(
            model_name='website',
            name='username',
        ),
        migrations.AddField(
            model_name='website',
            name='addressC',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AddField(
            model_name='website',
            name='descriptionC',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AddField(
            model_name='website',
            name='descriptionOneH',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AddField(
            model_name='website',
            name='descriptionThreeH',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AddField(
            model_name='website',
            name='descriptionTwoH',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AddField(
            model_name='website',
            name='emailC',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AddField(
            model_name='website',
            name='featureOneH',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AddField(
            model_name='website',
            name='featureThreeH',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AddField(
            model_name='website',
            name='featureTwoH',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AddField(
            model_name='website',
            name='headingOneH',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AddField(
            model_name='website',
            name='headingThreeH',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AddField(
            model_name='website',
            name='headingTwoH',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AddField(
            model_name='website',
            name='introductionA',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AddField(
            model_name='website',
            name='nameOfSiteH',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AddField(
            model_name='website',
            name='phoneC',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AddField(
            model_name='website',
            name='titleC',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AddField(
            model_name='website',
            name='whatWeDoA',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AlterField(
            model_name='website',
            name='user',
            field=models.CharField(default='default', max_length=255),
        ),
    ]
