# Generated by Django 3.0.5 on 2020-05-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='category',
            field=models.CharField(default='default', max_length=255),
        ),
    ]
