# Generated by Django 3.0.5 on 2020-05-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_website_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='photo_1',
            field=models.ImageField(blank=True, upload_to='%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='website',
            name='photo_2',
            field=models.ImageField(blank=True, upload_to='%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='website',
            name='photo_3',
            field=models.ImageField(blank=True, upload_to='%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='website',
            name='photo_4',
            field=models.ImageField(blank=True, upload_to='%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='website',
            name='photo_5',
            field=models.ImageField(blank=True, upload_to='%y/%m/%d'),
        ),
    ]
