# Generated by Django 3.0.5 on 2020-05-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20200529_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaWebFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=250)),
            ],
        ),
    ]
