# Generated by Django 3.0.5 on 2020-06-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20200531_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='emailC',
            field=models.EmailField(max_length=255),
        ),
    ]
