# Generated by Django 3.0.5 on 2020-06-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20200601_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='phoneC',
            field=models.BigIntegerField(),
        ),
    ]
