# Generated by Django 3.0.5 on 2020-06-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20200601_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='phoneC',
            field=models.CharField(max_length=255),
        ),
    ]
