# Generated by Django 3.0.5 on 2020-06-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_paiduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=255)),
                ('welcomeOne', models.CharField(default='welcomeOne', max_length=255)),
                ('welcomeOneDes', models.CharField(default='welcomeTwo', max_length=255)),
                ('welcomeTwoDes', models.CharField(default='welcomeTwoDes', max_length=255)),
                ('about', models.CharField(default='about', max_length=255)),
                ('galleryDes', models.CharField(default='galleryDes', max_length=255)),
                ('phone', models.IntegerField(default=100)),
                ('email', models.EmailField(default='admin@admin.com', max_length=255)),
                ('location', models.CharField(default='location', max_length=255)),
                ('aboutFooter', models.CharField(default='aboutFooter', max_length=255)),
                ('openingHours', models.CharField(default='openingHours', max_length=255)),
                ('fbLink', models.CharField(default='fbLink', max_length=255)),
                ('instaLink', models.CharField(default='instaLink', max_length=255)),
                ('youtubeLink', models.CharField(default='youtubeLink', max_length=255)),
                ('photo_1', models.FileField(default='photo_1', upload_to='')),
                ('photo_2', models.FileField(default='photo_2', upload_to='')),
                ('photo_3', models.FileField(default='photo_3', upload_to='')),
                ('photo_4', models.FileField(default='photo_4', upload_to='')),
                ('photo_5', models.FileField(default='photo_5', upload_to='')),
                ('photo_6', models.FileField(default='photo_6', upload_to='')),
                ('photo_7', models.FileField(default='photo_7', upload_to='')),
            ],
        ),
    ]
