# Generated by Django 3.0.5 on 2020-06-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20200606_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='backgroundColor',
            field=models.CharField(default='background Color', max_length=255),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='photo_1',
            field=models.ImageField(default='', upload_to='%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='photo_2',
            field=models.ImageField(default='', upload_to='%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='photo_3',
            field=models.ImageField(default='', upload_to='%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='photo_4',
            field=models.ImageField(default='', upload_to='%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='photo_5',
            field=models.ImageField(default='', upload_to='%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='photo_6',
            field=models.ImageField(default='', upload_to='%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='photo_7',
            field=models.ImageField(default='', upload_to='%y/%m/%d'),
        ),
    ]
