# Generated by Django 3.0.5 on 2020-06-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20200606_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='backgroundColor',
            field=models.CharField(default='backgroundColor', max_length=255),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='photo_1',
            field=models.FileField(default='photo_1', upload_to=''),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='photo_2',
            field=models.FileField(default='photo_2', upload_to=''),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='photo_3',
            field=models.FileField(default='photo_3', upload_to=''),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='photo_4',
            field=models.FileField(default='photo_4', upload_to=''),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='photo_5',
            field=models.FileField(default='photo_5', upload_to=''),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='photo_6',
            field=models.FileField(default='photo_6', upload_to=''),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='photo_7',
            field=models.FileField(default='photo_7', upload_to=''),
        ),
    ]
