# Generated by Django 3.0.5 on 2020-06-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_auto_20200606_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='user',
            field=models.CharField(default='user', max_length=255),
        ),
    ]
