# Generated by Django 3.0.5 on 2020-06-06 13:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_hotel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
