# Generated by Django 3.0.5 on 2020-05-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200524_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='menu',
        ),
        migrations.AddField(
            model_name='website',
            name='menus',
            field=models.CharField(default='yes', max_length=255),
        ),
    ]
