# Generated by Django 3.0.5 on 2020-05-25 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='id',
        ),
        migrations.AddField(
            model_name='website',
            name='user',
            field=models.CharField(default='admin', max_length=255, primary_key=True, serialize=False),
        ),
    ]
