# Generated by Django 3.0.5 on 2020-05-25 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_website_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='website',
            old_name='user',
            new_name='username',
        ),
    ]
