# Generated by Django 3.0.5 on 2020-05-25 08:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200525_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
