# Generated by Django 3.0.5 on 2020-05-25 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_website_created_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Website',
        ),
    ]
