# Generated by Django 3.0.5 on 2020-05-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20200525_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='addressC',
        ),
        migrations.RemoveField(
            model_name='website',
            name='descriptionC',
        ),
        migrations.RemoveField(
            model_name='website',
            name='descriptionOneH',
        ),
        migrations.RemoveField(
            model_name='website',
            name='descriptionThreeH',
        ),
        migrations.RemoveField(
            model_name='website',
            name='descriptionTwoH',
        ),
        migrations.RemoveField(
            model_name='website',
            name='emailC',
        ),
        migrations.RemoveField(
            model_name='website',
            name='featureOneH',
        ),
        migrations.RemoveField(
            model_name='website',
            name='featureThreeH',
        ),
        migrations.RemoveField(
            model_name='website',
            name='featureTwoH',
        ),
        migrations.RemoveField(
            model_name='website',
            name='headingOneH',
        ),
        migrations.RemoveField(
            model_name='website',
            name='headingThreeH',
        ),
        migrations.RemoveField(
            model_name='website',
            name='headingTwoH',
        ),
        migrations.RemoveField(
            model_name='website',
            name='introductionA',
        ),
        migrations.RemoveField(
            model_name='website',
            name='nameOfSiteH',
        ),
        migrations.RemoveField(
            model_name='website',
            name='phoneC',
        ),
        migrations.RemoveField(
            model_name='website',
            name='titleC',
        ),
        migrations.RemoveField(
            model_name='website',
            name='whatWeDoA',
        ),
        migrations.AddField(
            model_name='website',
            name='description',
            field=models.CharField(default='des', max_length=255),
        ),
        migrations.AddField(
            model_name='website',
            name='menu1',
            field=models.CharField(default='menu', max_length=255),
        ),
        migrations.AddField(
            model_name='website',
            name='menu2',
            field=models.CharField(default='menu', max_length=255),
        ),
        migrations.AddField(
            model_name='website',
            name='menu3',
            field=models.CharField(default='menu', max_length=255),
        ),
        migrations.AddField(
            model_name='website',
            name='menu4',
            field=models.CharField(default='menu', max_length=255),
        ),
        migrations.AddField(
            model_name='website',
            name='menu5',
            field=models.CharField(default='menu', max_length=255),
        ),
        migrations.AddField(
            model_name='website',
            name='menus',
            field=models.CharField(default='menu', max_length=255),
        ),
        migrations.AddField(
            model_name='website',
            name='title',
            field=models.CharField(default='title', max_length=255),
        ),
        migrations.AddField(
            model_name='website',
            name='username',
            field=models.CharField(default='admin', max_length=255),
        ),
        migrations.AlterField(
            model_name='website',
            name='user',
            field=models.CharField(default='user', max_length=255),
        ),
    ]
